In [1]:
import numpy as np

In [8]:
b = np.array([(1.5, 2, 3) ,(4, 5, 6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [28]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a = np.linspace(1, 100, 100)
a

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [38]:
np.full((9),7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7])

In [43]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [50]:
np.empty((9))

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [57]:
aa = np.random.random(9)
aa

array([0.44475566, 0.96364374, 0.32102091, 0.06101134, 0.5027279 ,
       0.03165552, 0.37139331, 0.05889848, 0.39847913])

In [53]:
a = np.full(9,100)

In [54]:
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [63]:
np.array_equal(a,a)

True