# 2. NumPy 배열

* NumPy에는 ndarray라는 데이터 타입의 배열이 생성된다.
* ndarray는 같은 타입의 데이터만 저장할 수 있다.
* Python의 list보다 계산 속도가 빠르다.

In [1]:
# import하기
import numpy as np

## 2-1. np.array() 함수로 생성하기
**1차원 배열 생성하기**

In [2]:
# 1차원 배열
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [3]:
# type 확인
type(arr)

numpy.ndarray

In [4]:
# array()에는 반드시 data가 1개 들어가야 한다!!
np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [1]:
# data type
arr.dtype

NameError: name 'arr' is not defined

In [2]:
# overflow 테스트
arr = np.array([2147483648, 2, 3, 4], dtype=np.int64)
arr

NameError: name 'np' is not defined

In [ ]:
arr = np.array([1, 2, 3, 4], dtype=np.float)
arr

In [ ]:
arr.dtype

In [ ]:
# shape : 각 차원의 배열의 size (모양)
arr.shape

In [ ]:
# size : 배열의 전체 element 수
arr.size

In [ ]:
# ndim : 차원의 수
arr.ndim

In [ ]:
arr = np.array([1, 2, 3, 3.14])
arr

In [ ]:
arr = np.array([1, 2, 3, 3.14],dtype=int)
arr

In [ ]:
# > : big-endian, < : little-endian
arr = np.array([1, 3.14, '1234'])
arr

In [ ]:
# 이미 있는 배열을 타입이 다른 다른 배열로 생성하기
new_arr = arr.astype(float)
new_arr

In [ ]:
arr.dtype, new_arr.dtype

## 2차원 배열 생성하기

In [ ]:
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],dtype=float)
arr2

In [ ]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

In [ ]:
new_arr = arr2.astype(int)
new_arr

## 2-2. np.arrange() 함수로 생성하기

In [ ]:
# 파이썬의 range
for i in range(0, 10, 2): # 0, 9
    print(i)

### 1차원 배열 생성하기

In [ ]:
# 1~10
arr = np.arange(1, 11, 2)
arr

### 2차원 배열 생성하기

In [ ]:
# 0~11
arr = np.arange(0, 12)
arr

In [ ]:
arr2 = arr.reshape((3, 4))
arr2

In [ ]:
arr, arr2

In [ ]:
arr2 = arr.reshape((3, 5))
arr2

In [ ]:
# 원본 배열의 shape를 변경하고자 할 경우
arr.shape = (3, 4)
arr

## 2-3. np.zeros() 함수

In [ ]:
# 1차원 배열
arr = np.zeros(4)
arr

In [ ]:
# 2차원 배열
arr2 = np.zeros((3,4))
arr2

### 2-4. np.ones() 함수

In [ ]:
# 1차원 배열
arr = np.ones(4)
arr

In [ ]:
# 2차원 배열
arr2 = np.ones((3, 4))
arr2

### 2-5. np.linspace() 함수

In [ ]:
arr = np.linspace(0, 10, 5)
arr

In [ ]:
arr = np.linspace(0, 10)
arr

In [ ]:
arr.shape

In [ ]:
arr2 = arr.reshape((10,5))
arr2

### 2-6. np.full() 함수

In [ ]:
# 특정 값으로 배열을 생성 할 경우
arr = np.full(4, 10)
arr

In [ ]:
arr2 = np.full((3, 4), 10)
arr2

In [ ]:
arr2 = np.full

### 2-7 np.eye() 함수

In [ ]:
# 단위 행렬 (항등 행렬)
arr = np.eye(5)
arr

### 2-8. np.random을 이용

In [2]:
arr2 = np.random.rand(3, 4)
arr2

array([[0.04227167, 0.09745164, 0.37639862, 0.48749381],
       [0.53247248, 0.96274588, 0.89967988, 0.07108627],
       [0.77892525, 0.25669118, 0.87335871, 0.81899392]])

In [3]:
arr = np.random.randint(5, size=10)
arr

array([3, 4, 1, 0, 4, 2, 0, 1, 2, 4])

In [4]:
arr2 = np.random.randint(1, 5, size = (3,4))
arr2

array([[1, 4, 4, 1],
       [2, 4, 4, 1],
       [2, 2, 2, 3]])

In [5]:
# 일정한 랜덤값을 만드려면?
np.random.seed(123)
np.random.rand(3, 4)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])

## 2-9. NumPy 배열 Save & Load

In [ ]:
arr = np.arange(5)
arr

In [ ]:
np.save('my_arr', arr)

In [ ]:
new_arr = np.load('my_arr.npy')
new_arr