# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [1]:
import numpy as np

In [6]:
# 1차원 배열
arr = np.arange(1, 11) # 1~10까지
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[1], arr[4], arr[-1]

(2, 5, 10)

In [8]:
arr[1]

2

In [12]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4) #1~12까지 3*4 2차원배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr2[0][1], arr2[1][2], arr2[-1][-1]

(2, 7, 12)

In [20]:
arr2[0, 1], arr2[1, 2], arr2[-1, -1]

(2, 7, 12)

## 5-2. 슬라이싱

In [21]:
# 1차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# 슬라이싱 [start:end:step]
arr[2:6]

array([3, 4, 5, 6])

In [28]:
# 3~끝까지
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# 처음~6까지
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [30]:
# 처음~끝까지
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# 슬라이싱한 후 값을 변경하면 원본 배열에 영향을 미칠까?
new_arr = arr[2:6]
new_arr

array([3, 4, 5, 6])

In [32]:
new_arr[0]=100
new_arr

array([100,   4,   5,   6])

In [33]:
arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [34]:
copy_arr = np.copy(arr)
copy_arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [35]:
arr[::2]

array([  1, 100,   5,   7,   9])

In [36]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
# 첫번째 행을 가져오기
arr2[:1]

array([[1, 2, 3, 4]])

In [50]:
# 세번쨰 열을 가져오기
arr2[:,2]

array([ 3,  7, 11])

In [62]:
# 첫번째, 두번째 행을 가져오기
arr2[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
# 두번째, 새번째 열을 가져오기
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [64]:
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [2]:
#1차원 
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
#[3, 6, 8]로 된 1차원 배열 만들기
np.array([arr[2], arr[5], arr[7]])

array([3, 6, 8])

In [3]:
# Fancy 인덱싱
# 인덱스로 배열 만들기
arr[[2, 5, 7]]

array([3, 6, 8])

In [5]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr[[0,2]]

array([1, 3])

In [8]:
# 슬라이싱
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [15]:
arr2[:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

# 5-4 Boolean 인덱싱

In [20]:
arr = np.arange(0, 5)
arr

array([0, 1, 2, 3, 4])

In [26]:
cond = [True, True, False, False, True]

In [24]:
# Boolean 인덱싱
arr[cond]

array([0, 1, 4])

In [30]:
arr > 2

array([False, False, False,  True,  True])

In [31]:
arr[arr > 2]

array([3, 4])

In [34]:
# 짝수 뽑기
arr % 2 == 0

array([ True, False,  True, False,  True])

In [35]:
arr[arr % 2 == 0]

array([0, 2, 4])

In [42]:
# 1보다 작거나 3보다 큰 수 (0, 4)
(arr < 1) | (arr > 3)
#괄호 꼭 붙이기

array([ True, False, False, False,  True])

In [43]:
arr[(arr < 1) | (arr > 3)]

array([0, 4])

In [47]:
# 2이상이면서 3이하인 수 (2, 3)
arr[(arr >= 2) & (arr <= 4)]

array([2, 3, 4])

In [67]:
np.sin(92)

-0.7794660696158047